### ISSUE TITLE
missing PSN_login

### ISSUE THREAD

**Issue by WildZarek** [AllynH/Destiny_Equip_Item#1]
Please add to repository this file, because it's needed.

**Comment by AllynH** [comment]
Hi there, 
You are correct the file is missing. Around the time I pushed this code  due to some of the Rise of Iron  changes, the PSN auth flow changed. 
I've since fixed the code and will push it to the repo :) 

I'm replying from my mobile, so I'll try to push it tonight.

**Comment by WildZarek** [comment]
Oh, it's ok.
I have my own **psn_login.py** file.
Basically, is the same shown in Bungie forum.
However, I can't login because the cookies doesn't match.
Python raises a **KeyError**. I will trying to fix my code, until this repo be updated.
Many thanks!

**Comment by AllynH** [comment]
Hi there,
The PSN_login.py file has been added, if you do a git pull you should get it.

Let me know if it works OK for you :)
